In [17]:
import numpy as np

In [18]:
array1 = np.array([1, 2, 3, 4, 5]) # this is a python list passed into an array, so make sure to 
print(array1)                      # structure the list into a homogenous type
print(type(array1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Dimensions in Arrays

In [19]:
#0-D arrays, these are also called Salars. Each elements is a 0 dimensional array

array2 = np.array(42)


In [81]:
#1-D arrat. These arrays have 0-D arrays as the elements. These ate the most basic and common arrays

array3 = np.array([1,2,3,4,5,6])
print(array3.shape, "\n")
print(np.transpose([array3]))


(6,) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [21]:
#2-D array. These arrays contain 1-D arrays as the elements. These are used to signify a matrix. 
#(Also called 2nd order tensers)

array4 = np.array([[1,2,3],[4,5,6]])
print(array4)

[[1 2 3]
 [4 5 6]]


In [22]:
#3-D array. These arrays have a 2-D arrays as its elements

array5 = np.array([[[1,2,3], [4,5,6]], [[1,2,3],[4,5,6]]])
print(array5)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [24]:
print(array2.ndim)#ndim isnt a method is an attribute of the class, easy to tell nsince no parentheses
print(array3.ndim)
print(array4.ndim)
print(array5.ndim)



0
1
2
3


Accessing the indexes of a np.array

In [32]:
print(array4[0])
print(array4[1])
print(array4[0] + array4[1])

add_array= np.array([[1,2,3,4], [5,6,7]])
print(add_array[0] + add_array[1])

[1 2 3]
[4 5 6]
[5 7 9]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [33]:
test_array = np.array([[1,2,3], [4,5,6]])
print(test_array.shape)


inner_array = test_array[0] # rows, colums
print(inner_array) 
print(inner_array[0])
# or directly
print(test_array[0][0])

(2, 3)
[1 2 3]
1
1


Slicing numpy arrays

In [59]:
array6 = np.array([[1,2,3],[4,5,6], [7,8,9], [10,11,12]])
print(array6[0:3]) # [:3] produces the same result
print(array6[2:])
print(array6.ndim) #checks the dimensions of the array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 7  8  9]
 [10 11 12]]
2


Arithmetic Operations
We can perform element-wise operations with scalar values

Aggregate Functions
We canperform aggregate 
-min
-max
-mean

In [45]:
sum= array6 + 1 #performs +1 to all elements in the array incrementing them by 1. We normally do this by a for loop
product= array6 * 2
division= array6 / 2


print(sum,"\n")
print(product, "\n")
print(division, "\n")


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]] 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]] 

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]
 [5.  5.5 6. ]] 



In [54]:
#.mean()
#.min()
#.max()
#.sum()

sum=np.sum(array3)
min=np.min(array3)
max=np.max(array3)
mean=np.mean(array3)

print(sum, min, max, mean)
print(type(sum))
print(sum + min)
print(sum + 3)

15 1 5 3.0
<class 'numpy.int32'>
16
18


Broadcasting wih a 2D array

In [56]:
multidimension_broadcast= array6 * 2
print(multidimension_broadcast)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]


Shaping with Numpy Arrays
- attribute shape

In [67]:
print(array6.shape) # 4 elements containing 3 elements; 2 dimensional array
                    #row and column structure with no depth behind it.
                    # is using an array attribute
print(np.shape(array6)) # is passing it into a function
print(array5.shape) # 2 elements containing 2 elements containing 2 elements; 3 dimensional array
                    #3rd dimension gives us our depth

(4, 3)
(4, 3)
(2, 2, 3)


Reshaping an Array

In [68]:
print(array3.shape, "\n") #1-D array print shows (5,)
print(np.reshape(array3, [2,3])) # needs a tuple
print(array3.reshape(2,3), "\n") #calling the method on the object array3 , doesn't need a tuple


print(np.reshape(array3, [3,2]))

(6,) 

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]] 

[[1 2]
 [3 4]
 [5 6]]


Transposing Arrays
-reverse the order of the axes

In [78]:
print(array4.shape)
print(array4, "\n")

print(array4.transpose())
print(array4.transpose().shape)


(2, 3)
[[1 2 3]
 [4 5 6]] 

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


Boolean Operations

In [84]:
a= np.array([1,2,3,4,5])
b= np.array([2,2,3,3,5])

c= a == b #checks each individual element vs the other in the same index
d= np.array_equal(a, b) # checks the full array against the other full array, each element is exactly the same in the same index

print(c)
print(d)

[False  True  True False  True]
False


In [83]:
a= np.array([True, True, False, False])
b= np.array([True, False, True, False])

c= np.logical_and(a, b)
print(c)

d= np.logical_or(a, b)
print(d)

[ True False False False]
[ True  True  True False]


Sorting
- arr.sort() changes the original array, but doesnt return anything
- np.sort() returns a new array

In [105]:
a= np.array([3,10,7,6,8,31,2,5])
print(a)
b= np.sort(a)[::-1] #to sort in descending order
c= a.sort()

print(a)
print(b)
print(c)

[ 3 10  7  6  8 31  2  5]
[ 2  3  5  6  7  8 10 31]
[31 10  8  7  6  5  3  2]
None
